- doctest.m
- doctest_run.m
Thanks for this software and thanks to original author too.
Here are some fixes to make doctest-for-matlab work on Octave.  Maybe some more to follow but these at least get it working for me!
> Fixes for Octave

- doctest.m
Use only the texinfo `@example` blocks for find tests.
> [WIP] octave: parse the texinfo for @example blocks

- doctest_run.m
Use `\S` instead of `\w` to in a regular expression.
Fixes #12.
> fix for output consisting only of symbols (non-words)

- doctest.m
- doctest_run.m
These basically improve Octave support, even when there are no ">>".  In principle, this makes no changes to how it works on Matlab and I've very lightly tested it on Matlab.
> Octave: split around "@result{}" blocks if no ">>" prompts

- doctest_compare.m
- doctest_run.m
Not sure this will work, maybe don't merge yet...
But it will in principle fix #14.
I know I'm relying on this bug because I often don't include "ans = " in my doctests!  But I may try to add that feature separately.
> match the whole string: anchor the regexp ends

- doctest.m
List of possible extensions taken from [1].  Yes, 'tex' really is
valid: they are also .tex files (I never knew).  Fixes #22.
[1]
http://www.gnu.org/software/texinfo/manual/texinfo/html_node/Minimum.html
> Test more extensions for texinfo files

- doctest_run.m
Tested on 2015a.  Maybe this syntax was ok in earlier versions?
> syntax error fix on Matlab

- doctest.m
- doctest_run.m
reformat and comment the regex.  2nd commit has the actual minor change.
tested, still works on Matlab.
> Octave: multiline input fix

- Makefile
- NEWS
- inst/doctest.m
- inst/private/doctest_collect.m
- inst/private/doctest_colors.m
- inst/private/doctest_run.m
See #37 and #31 for related discussion. The new summary format is as follows:
~~~
octave:5> doctest({'doctest', 'doctest_run', 'doctest_compare', 'doctest_collect', 'doctest_colors'})
doctest ................................................ PASS    6/6   
doctest_run ............................................ NO TESTS
doctest_compare ........................................ PASS    2/2   
doctest_collect ........................................ NO TESTS
doctest_colors ......................................... NO TESTS
Summary:
PASS    8/8   
5/5 targets passed, 3 without tests.
octave:6> 
~~~
~~~
octave:4> doctest({'doctest', 'doctest_run', 'cat', 'doctest_compare', 'more', 'test.texinfo', 'doctest'})
doctest ................................................ PASS    6/6   
doctest_run …
> Suggestion for the new doctest API

- inst/private/doctest_compare.m
> Allow '***' to match empty string

- NEWS
- inst/doctest.m
- inst/private/doctest_run.m
- test/test_skip.m
- test/test_skip_only_one.m
Not yet tested with texinfo and no `@comment` support.
Should be merge-able or you can wait until I try the texinfo stuff...
> Implement doctest skip

- inst/private/doctest_collect.m
Preferable IMHO to recompute 'running_octave' lots of times than risk
shared namespaces.
> No nested functions

- inst/doctest.m
Clean up, shorten, don't mention Matlab so much, other minor edits.
> reword `help doctest` a bit

- NEWS
- inst/doctest.m
- inst/private/doctest_run.m
- test/test_whitespace.m
This is more consistent with Python.
Fixes #76.  Also fix minor typo in NEWS.
> Change to NORMALIZE_WHITESPACE

- Makefile
- inst/private/doctest_collect.m
- test/test_skip_malformed.texinfo
Tests marked `doctest: +SKIP` can nonetheless raise Extraction Errrors.
No fix yet, just the test itself ;-)
*Background:* This happens a lot in core octave where `@example` seems to be often used as `@verbatim` and in particular as the alternative to `@tex` when writing mathematics.  Maybe they should just use `@verbatim` but its not so easy because that changes indentation.  Easier at least in the short term to just mark them as `doctest: +SKIP`.
> extract error for "+SKIP" in a malformed @example block

- inst/doctest.m
- inst/private/doctest_default_directives.m
- inst/private/doctest_run.m
Fixes #74.
@catch22 this adds some input parsing.  Is it compatible with your plans?  Or you have a better way?
I left a stub for future `-recursive`.
I did not allow settings defaults for XFAIL and SKIP could do so.
> Allow default values for directives to be overriden on cmdline

- Makefile
- inst/doctest.m
- util/convert_comments.m
@catch22 Here's a utility from Symbolic that I use to generate proper matlab-style docs from texinfo.
1.  In this PR, I hack the two-blank-lines rule into the texinfo: this does effect how `help doctest` looks in Octave: it adds two blank lines instead of one after each example...
2.  Alternatively, I could just use `sed` in the Makefile to do this on a temporary copy file during conversion, which would leave the Octave version untouched...
What do you think?  HTML output is unaffected by either approach.
> matlab package: autogenerate docs from Octave texinfo

- NEWS
- inst/private/doctest_collect.m
- test/.hidden/test_dont_run.m
- test/@test_class/test_class.m
- test/@test_class/test_method.m
- test/private/test_dont_run.m
- test/private/test_in_private_dir.m
- test/test_no_docs.m
- test/test_not_an_mfile.txt
- test/test_shadow/test_in_shadow_dir.m
Some fixes for various bugs.  I did not add config flags: I figure we can add later if there is a use case...
Most importantly it stays out of one's `.git`
> Ignore hidden dirs, and non .m/texinfo files

- inst/doctest.m
- inst/private/doctest_collect.m
This is on top of some other changes, just last couple commits...
current result for `doctest . recursive`:
````
Doctest v0.4.1-dev: this is Free Software without warranty, see source.
0.4.0/
inst/
doctest.m ............................................ PASS   10/10  
src/
test/
test_class ........................................... PASS    1/1   
@test_class/test_class ............................... PASS    1/1   
@test_class/test_method .............................. PASS    1/1   
test_classdef ........................................ NO TESTS
@test_classdef/amethod ............................... NO TESTS
@test_classdef/test_classdef ......................... NO TESTS
test_shadow .......................................... PASS    1/1   
@test_shadow/test_shadow …
```
> indent with each subdir during traversal

- DESCRIPTION
*Not* a license change, just a renaming it.  This makes it match the
license name in .metainfo.xml.
> Alternate name for license in DESCRIPTION

- inst/doctest.m
> Deprecate support for specifying directives in doctest call

- inst/private/doctest_run.m
- test/test_comments_with_directives.m
This fixes #144.  This also means we can simply the regexp so
probably fewer corner cases.  Downside is the conditional code
cannot contain the chars `#` or `%`: this is not anticipated to
cause much hardship.
> Comments can robustly appear after directives

- .travis.yml
Some time ago we stopped supporting it, so drop from our CI tests.
@catch22 this ok with you?
> Stop testing on Octave 3.8

- inst/private/doctest_compare.m
- test/test_ellipsis_match_empty.m
- test/test_ellipsis_match_whitespace.m
This is on top of a few other things, but the important commit is:
```
rework "compare" to avoid changing both strings
Instead, try to make a regular expression from "WANT" and then
match that against "GOT".  Before, we did a bit of both so this
should be more maintainable.
```
This makes slight changes to the behaviour of `...`.  I think it also fixes #153.  Although slight changes to the tests I did there...
> refactor doctest_compare

- NEWS
- inst/private/doctest_datastore.m
- inst/private/doctest_format_exception.m
- inst/private/doctest_join_conditions.m
- inst/private/doctest_run_docstring.m
- inst/private/doctest_run_tests.m
- test/test_clear.m
- test/test_clear_all_first.m
- test/test_clear_isoctave.m
Fixes #149.  @catch22 what do you think?
There is a bit of complexity coming from `DOCTEST__results` and `DOCTEST__tests` being slightly different (b/c of skipped tests).  I'm thinking of refactoring a bit to make the input a cell array of tests (instead of a struct array).  But for now, this maintains the status quo.
Bikeshedding this "datastore" object and its "methods" is certainly welcome!
> Support "clear"

- inst/private/doctest_collect.m
Due to an upstream bug https://savannah.gnu.org/bugs/index.php?48041
if "help myclass" or `help @myclass/myclass` is called on a classdef
class, then "help myclass/mymethod" won't work during that session.
So we make an extra loop over the class, accessing the help text for
each non-constructor method.  Octave then seems to cache this text
(or something) and the tests work.
Performance: this workaround adds a very small overhead (0.3s on
Symbolic's large `@sym` class), compared to the cost of extracting
all the tests (many seconds on same example).  Nonetheless, it
should be removed once the upstream bug is fixed.
Fixes #135.  Well, workaround anyway.
> Temporary workaround for "help myclass" breaking method tests

- inst/doctest.m
- inst/private/doctest_collect.m
"help meh.oct" doesn't work so strip the ".oct" if specified.  This
makes `doctest .` work.  If both meh.oct and meh.m are present,
"help meh" will get the .oct file; this does the same.  `doctest meh.m`
will explicitly test the .m file.  This may work for mex files although
I haven't tested that.
> Find tests in .oct files

- test/test_format.m
`format long` behaves differently sometime between 4.2 and 5.1 for numbers
less than 1 (such as 1/6 used in this test).
Adjust the test to 10/6 instead, which gives same result.  Tested on 4.2,
5.0.91, 6.0, and Matlab.
> adjust test for "format long" changes

- DESCRIPTION
- NEWS
- inst/doctest.m
Rational documented at [1].
[1] https://savannah.gnu.org/bugs/?55829
> use "+" postfix for developement version

- inst/private/doctest_format_exception.m
This should be harmless and will look a little better if there are
say blank lines at then end of an error message.
> trim blank whitespace from around error messages

- .travis.yml
- Makefile
Convert Travis CI to run all tests in the `mtmiller/octave` Docker image instead of the native Travis Ubuntu environment.
Addresses #204
> Convert CI to Docker

- .travis.yml
A snapshot of Octave's development branch is available now, so add testing against that back into the CI matrix.
> test Octave development version again

- Makefile
Mostly fixes #216.
If you're on a BSD system that does not have GNU tar installed, it will still fall back to using the system BSD tar, and then create an empty tarball.
> Detect and use GNU tar (so it works on BSD systems)

- inst/private/doctest_run_docstring.m
- test/bist.m
- test/test_error.m
- test/test_tab_before_prompt.m
Fixes #237 by adding a blank space to the prompt.
Factor the prompt itself out of the regex.
There was some inconsistency about `\s*` or ` *`: I assume that was an accident and used `\s*` before the prompt in both the beginning and end of the test.  Added a test for this.
> improve prompt matching in regex

- Makefile
Fixes #232.
Is this the right fix?  @mtmiller or anyone else who knows Makefiles
> [maint] Makefile: build matlab pkg before matlab_test

- NEWS
- inst/doctest.m
- inst/private/doctest_collect.m
- inst/private/doctest_compare.m
- inst/private/doctest_format_exception.m
- inst/private/doctest_run_tests.m
- test/test_clear.m
- test/test_clear_all_first.m
- test/test_clear_isoctave.m
- test/test_deprecated.m
- test/test_error.m
- test/test_error.texinfo
In most cases, prepend `error: ` like Octave does.  In special cases
(currently `parse error:` but maybe others later) we do not do this
prepending.
This is a partial fix for Issue #238.  But no changes yet on Matlab
and no deprecation of `???`.
> Remove `???` from Octave/Matlab errors

- inst/private/doctest_collect.m
- test/test_error.texinfo
Treat `@error` the same way we do `@result`.  I'll admit I didn't look too carefully but I did need this for tests with `@error` to pass...
> Support texinfo macro `@error`

- Makefile
- test_extra/run_tests.m
- test_extra/test_encoding/test_bytecount_CP1252.m
@mmuetzel I went and learning a little and tried to write a test that convinces me that the strings are being loaded properly into utf-8.
> test: CP1252 encoding, check utf-8 conversion

- test/test_angle_brackets.m
See Issue #231.  Maybe not completely fixed.  Not closing.
> Fix test broken on matlab for string indicators

- NEWS
- inst/private/doctest_collect.m
- test/bist.m
Fixes Issue #203.  Note that we still don't iterate over classes using
class.method: that is a later change for Issue #264.
- Octave 6, tests protected on earlier versions
> Octave: allow doctest class.method

- .github/workflows/main.yml
"latest" is currently just 7.2.0 but I think this future proofs things a bit.
Fixes #270.
> CI: run octave 7.2.0 and "latest"

- NEWS
- inst/private/doctest_collect.m
- test/bist.m
Fixes #264.  Fixes #261.
I'm currently thinking to leave this for 0.9.0 as it seems like a big change.  OTOH, its clear `cls.method` is the best supported way of access classdef method help, and this falls back on `@cls/method` for old-style classes...
Maybe we can do a 0.8.0 and soon after do a 0.9.0.
> Use cls dot method for testing classdef classes

- io.github.gnu_octave.doctest.metainfo.xml
See [1].
[1] https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
> metainfo: developer_name is deprecated

- .github/workflows/main.yml
Its not as simple as on GitLab, b/c we can only (easily) run Ubuntu images and their Appstream package is too old (< 0.16.3)
Instead we install Flatpak, add Flathub and pull `org.freedesktop.appstream.cli`, which seems to work but feels a bit "heavy".
> CI: validate the metainfo

- inst/private/doctest_collect.m
- test/bist.m
- test_extra/run_tests.m
Fixes #268!  Nice!  But some other issues: #288, #289.u
> porting to Octave 9
