gnu-octave/octave-doctest

- doctest_run.m
> fake evalc fixes for octave and matlab

- doctest.m
more like workaround: just call the relevant routine once
after each function.  Fixes #3.
> fix results display for classes

- doctest.m
> doctest.m can return the number of tests and number failed

- doctest.m
Add a more elaborate summary
Fixes #23.
> More summary

- make_octaveforge_pkg.sh
- octaveforge_pkg/CONTRIBUTORS
- octaveforge_pkg/DESCRIPTION
- octaveforge_pkg/NEWS
This requires a tarball with files in special places.  Add a
script that makes such a tarball.  Add the various support files.
> Files to support an Octave-Forge package

- doctest.m
Purple looks ok on light and dark backgrounds.
> colours: use symbolic names and change yellow to purple

- COPYING
- DESCRIPTION
- inst/doctest.m
@catch22 listed you as a maintainer for DESCRIPTION file.  That ok?
> update copyright notice, other minor changes

- Makefile
- inst/private/doctest_compare.m
- test/test_angle_brackets.m
- test/test_blank_match.m
- test/test_compare_backspace.m
- test/test_compare_hyperlinks.m
Start collecting test cases so we can add tests as we fix bugs.
At least one of these won't pass except with Octave from hg, so maybe no need to hook up to "make test", at least not immediately.
@catch22 do you think we should merge this now?  Is a bunch of .m files in `test/` the best approach?
> Add a testsuite to update as we fix bugs

- inst/private/doctest_collect.m
Trying to fix #53.  Just diagnostics for now...
> fix class input on recent Octave

- inst/doctest.m
- inst/private/doctest_collect.m
- inst/private/doctest_colors.m
- inst/private/doctest_run.m
- inst/private/is_octave.m
Do some benchmarking for best approach to this function, see
table in comments of is_octave.m
> split out an is_octave() function

- Makefile
- inst/private/doctest_collect.m
- inst/private/doctest_run.m
- test/test_comments.texinfo
- test/test_skip_comments.texinfo
> Texinfo comments

- Makefile
- NEWS
- inst/doctest.m
- inst/private/doctest_compare.m
- inst/private/doctest_run.m
- test/test_whitespace.m
Heads up, the individual commits might be easier to review...
> directives to control whitespace

- Makefile
- NEWS
- inst/doctest.m
- inst/private/doctest_compare.m
- inst/private/doctest_run.m
- test/test_blank_match.m
- test/test_ellipsis.m
- test/test_warning.m
> Use ellipsis instead of *** wilcards and provide -ELLIPSIS option.

- .gitattributes
- Makefile
Fixed #78 and added targets for Octave package release
> Improved Maintainer Makefile

- NEWS
- inst/doctest.m
I'm not convinced we want this, especially as we might still be thinking about #95.  But here's a branch that adds it...
> Add a "-nonrecursive" command line option

- inst/private/doctest_compare.m
- test/test_ellipsis_match_empty.m
- test/test_ellipsis_match_whitespace.m
No fix yet, just some failing tests...
> [wip] Tests for ellipses and whitespace issue #153

- inst/doctest.m
- inst/private/doctest_collect.m
- inst/private/doctest_colors.m
- inst/private/doctest_compare.m
- inst/private/doctest_datastore.m
- inst/private/doctest_default_directives.m
- inst/private/doctest_format_exception.m
- inst/private/doctest_join_conditions.m
- inst/private/doctest_run_docstring.m
- inst/private/doctest_run_tests.m
- inst/private/is_octave.m
This is on top of PR #169.  
I tried to track changes back enough to give appropriate attribution.  Of course, it can be corrected if I've missed something/someone.
> Add license headers to files in private/

- Makefile
- util/convert_comments.m
Note, we don't tag the repo anymore, that happens after a review of the release.
@oheim could you offer some light review of the Octave part of this?  It should be very similar to what is done in Symbolic in the last release.
> [maint] Makefile improvements for current Octave Forge practices

- .travis.yml
This appears to fix #157 (see https://travis-ci.org/catch22/octave-doctest/builds/290707102).
> CI: Use travis APT add-on

- test/test_multi_return.texinfo
Avoid upstream issue https://savannah.gnu.org/bugs/index.php?52285
Fixes issue #175.
> Use a different test for warning

- DESCRIPTION
- octave-doctest.metainfo.xml
Mainly to follow practice on Octave Forge website.
> update project metainfo

- .travis.yml
- Makefile
@mtmiller does this look ok to you?
> [maint] run CI on more octave versions

- inst/doctest.m
- inst/private/doctest_collect.m
This is for discussion regarding #201
> WIP: Add a hidden "-quiet" directive

- NEWS
- inst/private/doctest_collect.m
- test/bist.m
Here's my attempt at refactoring based on the discussion in #196, as well as fixing a few other bugs. 
~~This is on top of my BIST work: `doctest_collect` changes are the real thing here.~~
Updated: rebased.
> Changes to `doctest class`

- CONTRIBUTORS
- Makefile
@skycaptain if you are happy with how your name is written, give this a "+1" and I'll merge it.
> [maint] Update copyright and contributors

- README.md
- inst/doctest.m
- test/@test_class/test_class.m
- test/@test_class/test_method.m
- test/examples/greet.m
- test/test_compare_backspace.m
- test/test_ellipsis.m
Fixes #231. I've only changed the tests affected by this bug. Others are still failing. Tested with Matlab R2019b and Octave 5.1.0
> Fixed #231

- inst/doctest.m
> Simplify NORMALIZE_WHITESPACE example

- inst/doctest.m
> strings are now valid matlab so use some other example

- test/test_methods_in_subdir/@logical/mynewmethod.m
Tested with Matlab 2019b and Octave 5.1.0
> Fixes #234

- test/@test_classdef/test_classdef.m
- test_extra/run_tests.m
My attempts at documenting via tests and xtests, the state of #220.
Fixes #221.
> test: Classdef counting
